title: Correlated Content
domain: "correlatedcontent.com"
baseurl: "" 
permalink: /blog/:title.html
url: "https://www.correlatedcontent.com"

author:
  name: Lodewijk Sioen

excerpt_separator: "<!--excerpt-->"

collections:
  posts:
    permalink: /blog/:year/:month/:day/:slugified_categories/:title

kramdown:
  header_offset: 2

feed:
  excerpt_only: true

# Build settings
plugins:
  - jekyll-feed

# Exclude from processing.
exclude:
  - _run.bat
  - CorrelatedContent.code-workspace
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
